In [9]:
import numpy as np
weight_hid_to_out = np.random.rand(6,1)

In [15]:
weight_hid_to_out

array([[0.40037409],
       [0.71355378],
       [0.68819741],
       [0.54239472],
       [0.68295447],
       [0.96063641]])

In [19]:
y = 5
y_hat = np.array([3])
error = y - y_hat

hidden_error = error * weight_hid_to_out.T
hidden_error

array([[0.80074818, 1.42710757, 1.37639482, 1.08478945, 1.36590894,
        1.92127283]])

In [13]:
hid_err = error * weight_hid_to_out
hid_err.shape

(6, 1)

In [20]:
X = np.array([4,6,8,9])
X[:, None].shape

(4, 1)

In [25]:
import torch
import torch.nn as nn

In [22]:
np.random.rand(1,6)

array([[0.93568029, 0.26708892, 0.43923858, 0.272292  , 0.08545174,
        0.18475155]])

In [23]:
torch.rand(1,6)

tensor([[0.4088, 0.1468, 0.1783, 0.9239, 0.2200, 0.6791]])

In [26]:
in_hid = nn.Linear(4,8)
hid_out = nn.Linear(8,1)

In [29]:
input = torch.rand(1,4)
x = in_hid.forward(input)
x = hid_out.forward(x)
x

tensor([[-0.2166]], grad_fn=<AddmmBackward>)

In [1]:
%matplotlib inline
%load_ext autoreload
%autoreload 2

In [5]:
import pandas as pd
from torchwisdom.statemgr.state import StateManager, Logger, Store

In [6]:
df = pd.read_csv('~/.torchwisdom/state/main.csv')
df

id  name  desc  \
0  2c1fbdf09b53e928a1661e1f0b46b055a1652ae1   NaN   NaN   

                     datetime  
0  2019-04-17 10:21:06.039692

In [14]:
m = StateManager()
m.dataframe()

id  name  desc  \
0  2c1fbdf09b53e928a1661e1f0b46b055a1652ae1   NaN   NaN   

                     datetime  
0  2019-04-17 10:21:06.039692

In [16]:
m.id

'9fd0a6a8926f83924e0c50ea0de43aec789c2c2f'

In [17]:
m.load('2c1fbdf09b53e928a1661e1f0b46b055a1652ae1')

{'data': {'dataset': {'trainset': {}, 'validset': {}, 'testset': {}},
  'dataloader': {'train_loader': {}, 'valid_loader': {}}},
 'model': {'state_dict': None, 'arch': None, 'object': None},
 'metrics': {'train': {'loss': {'val': [],
    'mean': [],
    'std': [],
    'epoch': []}},
  'valid': {'loss': {'val': [], 'mean': [], 'std': [], 'epoch': []}},
  'test': {'loss': {'val': [], 'mean': [], 'std': [], 'epoch': []}}},
 'optimizer': {},
 'scheduler': {},
 'trainer': {'id': '',
  'name': '',
  'desc': '',
  'epoch': {'start': 0,
   'curr': 0,
   'num': 0,
   'time': [],
   'time_start': 0,
   'time_end': 0,
   'remain': []},
  'created': '',
  'modified': ''}}

In [18]:
m.state

{'data': {'dataset': {'trainset': {}, 'validset': {}, 'testset': {}},
  'dataloader': {'train_loader': {}, 'valid_loader': {}}},
 'model': {'state_dict': None, 'arch': None, 'object': None},
 'metrics': {'train': {'loss': {'val': [],
    'mean': [],
    'std': [],
    'epoch': []}},
  'valid': {'loss': {'val': [], 'mean': [], 'std': [], 'epoch': []}},
  'test': {'loss': {'val': [], 'mean': [], 'std': [], 'epoch': []}}},
 'optimizer': {},
 'scheduler': {},
 'trainer': {'id': '',
  'name': '',
  'desc': '',
  'epoch': {'start': 0,
   'curr': 0,
   'num': 0,
   'time': [],
   'time_start': 0,
   'time_end': 0,
   'remain': []},
  'created': '',
  'modified': ''}}